### ISSUE TITLE
OSx - Can't run on 127.0.0.1 without any option

### ISSUE THREAD

**Issue by SakiiR** [brandonskerritt/RustScan#21]
For some reasons ^^

<img width="988" alt="sc 2020-07-23 at 11 13 19" src="https://user-images.githubusercontent.com/9950578/88270862-94d0c900-ccd6-11ea-8bbb-c825805ad332.png">

**Comment by brandonskerritt** [comment]
Hey! Your OS is using too many open files.
There's a hard limit on how many open files you're allowed at once, it differs from OS to OS. I found 5000 to work on Linux, but Mac OS seems to have some problems with this.

https://docs.oracle.com/cd/E19623-01/820-6168/file-descriptor-requirements.html

There are 2 ways to solve this:
1. Reduce batch size to 2500 with `rustscan -b 2500`. Note: this will slow things down :cry: but it'll mean you can run it. 
2. Increase the open file limit `ulimit -n 65535`. This _may_ cause some problems. I haven't fully tested it yet!

If you wouldn't mind, please can you share your Mac specs? I am trying to build the "best" default batch size, but I only have Linux samples (due to only using Linux / Linux virtual machines). If you share your specs, I can better workout the best batch size :)

**Comment by SakiiR** [comment]
Hey ! fast answer !

I completely understood the issue and tried to pass the `-B` option, then tried the `-b` etc etc.

<img width="497" alt="sc 2020-07-23 at 11 31 52" src="https://user-images.githubusercontent.com/9950578/88271885-23921580-ccd8-11ea-9996-2145a87b84e7.png">

**Comment by SakiiR** [comment]
I usually do not use OSx at all. It is just for work. 

Sorry, can't send you my specs :(

**Comment by brandonskerritt** [comment]
Hahahahah wow! How many open files do you have? :joy: I thought the absolute minimum would be 500? So strange. The problem is, the closer we get to a batch size of 0, the more sequential it'll be (and that would suck, as it loses all speed).

Out of curiosity, how low can you go before it does start to work? Try 100? And then 10? I hope it at least _runs_ for you.

According to Google, Mac OS has a limit of 12k open files. Which is really low compared to Linux.

Can you run these 3 commands:

```
ulimit -a
ulimit -Hn
ulimit -Sn
```

Which says what the max open file limit is on your machine. Using that, I can provide better support :)

**Comment by SakiiR** [comment]
Haha funny, it is only 256 actually !

<img width="454" alt="sc 2020-07-23 at 11 40 35" src="https://user-images.githubusercontent.com/9950578/88272684-61dc0480-ccd9-11ea-8dd8-d9aae05e0ebf.png">

**Comment by SakiiR** [comment]
Ahah funny ! it is actually 256 FDs :D 

<img width="489" alt="sc 2020-07-23 at 11 41 22" src="https://user-images.githubusercontent.com/9950578/88272741-7ae4b580-ccd9-11ea-9429-682531dd3d11.png">

**Comment by SakiiR** [comment]
`rustscan  127.0.0.1 -b 255` OK
`rustscan  127.0.0.1 -b 256` KO

:)

**Comment by brandonskerritt** [comment]
Hahahah!

I'm not sure on the commands, but this is a work laptop -- do you have root?
I can change the limit with `ulimit -n <new limit>` but it requires root I think.

The soft limit can be changed (without root) with `ulimit -S <new limit>`

It would be beneficial to increase it somewhat (I'm not sure how much, though). Since 256 ports at a time is very slow.

For reference, if you increase it to 65535 and do -b 65535 it will scan all 65k ports at the exact same time (but I imagine both your computer and the server would freak out) :joy:

**Comment by SakiiR** [comment]
I think the best way would be to use the `ulimit` syscall to read the value and then set it automatically depending on what is available 👍 

And then, notify the user about this "The current FD limit is too small, increase is blah blah".

**Comment by SakiiR** [comment]
Yes, I would not recommend to be so fast on one single IP.

In real life, you never know what is going to handle ur packets (eq, a bugged firewall might break off)

**Comment by brandonskerritt** [comment]
> I think the best way would be to use the `ulimit` syscall to read the value and then set it automatically depending on what is available +1
> 
> And then, notify the user about this "The current FD limit is too small, increase is blah blah".

This is actually what I was planning on doing, the error message you see says to decrease the batch size -- but it would be far better for me to read the FD limit. Let me make this into its own issue, so I can track feature requests :D
